In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#square root
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
#Exponential
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
#binary functions
A = np.random.randn(10)
A

array([ 0.75168147,  1.82310184, -0.01913028,  2.81804593,  0.25833095,
        1.06521007, -0.56897294, -1.17867138,  0.10420686,  1.15577203])

In [7]:
B = np.random.randn(10)
B

array([-1.53465421, -1.16558652,  1.00126944,  1.01264913,  0.07061381,
       -1.93343068,  0.52149461, -0.38993094,  1.34500776, -0.7472262 ])

In [8]:
# Binary Functions
np.add(A,B)

array([-0.78297274,  0.65751532,  0.98213916,  3.83069506,  0.32894476,
       -0.86822062, -0.04747833, -1.56860232,  1.44921462,  0.40854583])

In [9]:
np.maximum(A,B) # Compares values at each index and outputs the max

array([ 0.75168147,  1.82310184,  1.00126944,  2.81804593,  0.25833095,
        1.06521007,  0.52149461, -0.38993094,  1.34500776,  1.15577203])

In [10]:
np.minimum(A,B)

array([-1.53465421, -1.16558652, -0.01913028,  1.01264913,  0.07061381,
       -1.93343068, -0.56897294, -1.17867138,  0.10420686, -0.7472262 ])

In [12]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True